import { IProductInsert, IProductSelect } from "@/lib/types";

export const products: IProductSelect[] = [
  {
    id: "TSHIRT001",
    name: "Футболка чоловіча",
    article: "TSHIRT001",
    price: { main: 1500, discount: 1200 },
    image: "/image.png",
    color: "#FFFFFF",
    nameColor: "Білий",
    count: 10,
    maxCount: 10,
  },
  {
    id: "SNEAKERS045",
    name: "Кросівки спортивні",
    article: "SNEAKERS045",
    price: { main: 3200, discount: 2800 },
    image: "/image-2.png",
    color: "#000000",
    nameColor: "Чорний",
    count: 5,
    maxCount: 10,
  },
  {
    id: "BACKPACK210",
    name: "Рюкзак міський",
    article: "BACKPACK210",
    price: { main: 2200 },
    image: "/image-3.png",
    color: "#808080",
    nameColor: "Сірий",
    count: 15,
    maxCount: 30,
  },
  {
    id: "JACKET032",
    name: "Куртка демісезонна",
    article: "JACKET032",
    price: { main: 4800, discount: 4300 },
    image: "/image-4.png",
    color: "#0000FF",
    nameColor: "Синій",
    count: 8,
    maxCount: 20,
  },
  {
    id: "JEANS119",
    name: "Джинси чоловічі",
    article: "JEANS119",
    price: { main: 2600, discount: 2300 },
    image: "/image.png",
    color: "#0A1F44",
    nameColor: "Темно-синій",
    count: 12,
    maxCount: 20,
  },
  {
    id: "WAISTBAG007",
    name: "Сумка поясна",
    article: "WAISTBAG007",
    price: { main: 900 },
    image: "/image-2.png",
    color: "#000000",
    nameColor: "Чорний",
    count: 20,
    maxCount: 30,
  },
  {
    id: "WATCH501",
    name: "Годинник наручний",
    article: "WATCH501",
    price: { main: 5500, discount: 4999 },
    image: "/image-3.png",
    color: "#C0C0C0",
    nameColor: "Сірий",
    count: 6,
    maxCount: 10,
  },
  {
    id: "SUNGLASSES042",
    name: "Окуляри сонцезахисні",
    article: "SUNGLASSES042",
    price: { main: 1800, discount: 1500 },
    image: "/image-4.png",
    color: "#000000",
    nameColor: "Чорний",
    count: 25,
    maxCount: 30,
  },
  {
    id: "SHIRT223",
    name: "Сорочка класична",
    article: "SHIRT223",
    price: { main: 2000 },
    image: "/image.png",
    color: "#FFFFFF",
    nameColor: "Білий",
    count: 9,
    maxCount: 10,
  },
  {
    id: "BLAZER034",
    name: "Піджак чоловічий",
    article: "BLAZER034",
    price: { main: 6700, discount: 5999 },
    image: "/image-2.png",
    color: "#808080",
    nameColor: "Сірий",
    count: 4,
    maxCount: 10,
  },
];

export const categories = [
  { title: "Сукні", image: "/image-4.png" },
  { title: "Костюми", image: "/image-3.png" },
  { title: "Аксесуари", image: "/image-2.png" },
  { title: "Куртки", image: "/image.png" },
];

export const product: IProductInsert = {
  id: "245456",
  name: "Назва товару",
  article: "245456",
  price: {
    main: 1500,
    discount: 1000,
  },
  colors: [
    {
      color: "#4F4631",
      nameColor: "Коричневий",
      count: 10,
      images: [
        { link: "/image.png", count: 0 },
        { link: "/image-2.png", count: 1 },
        { link: "/image-3.png", count: 2 },
        { link: "/image-4.png", count: 3 },
      ],
    },
    {
      color: "#314F4A",
      nameColor: "Зелений",
      count: 30,
      images: [
        { link: "/image.png", count: 0 },
        { link: "/image-2.png", count: 2 },
        { link: "/image-3.png", count: 3 },
        { link: "/image-4.png", count: 1 },
      ],
    },
    {
      color: "#31344F",
      nameColor: "Синій",
      count: 5,
      images: [
        { link: "/image.png", count: 0 },
        { link: "/image-2.png", count: 1 },
        { link: "/image-3.png", count: 3 },
        { link: "/image-4.png", count: 2 },
      ],
    },
  ],
  descriptions: [
    {
      title: "Опис / Склад та догляд",
      description:
        "Онови свій стиль з нашим якісним та трендовим одягом! Ця модель поєднує комфорт, елегантний дизайн та довговічні матеріали, що ідеально підходять для будь-яких випадків – від повсякденних прогулянок до особливих подій.",
    },
    {
      title: "Умови доставки та повернення",
      description:
        "Онови свій стиль з нашим якісним та трендовим одягом! Ця модель поєднує комфорт, елегантний дизайн та довговічні матеріали, що ідеально підходять для будь-яких випадків – від повсякденних прогулянок до особливих подій.",
    },
  ],
};
